services:
  dbeaver-proxy-to-mistral:
    image: ghcr.io/isyuricunha/dbeaver-proxy-to-mistral:latest
    ports:
      - "60916:60916"
    environment:
      MISTRAL_API_KEY: "xdx"
      MISTRAL_BASE_URL: "https://api.mistral.ai/v1"
      MISTRAL_MODEL: "mistral-large-latest"
      MISTRAL_MODELS: "mistral-large-latest"
      HOST: "0.0.0.0"
      PORT: "60916"
      REQUEST_TIMEOUT_SECONDS: "60"
    restart: unless-stopped
